obstacle_range: 2.0
raytrace_range: 3.0
footprint: [[-0.2, -0.15], [0.2, -0.15], [0.2, 0.15], [-0.2, 0.15]]
#footprint_inflation: 0.01
# robot_radius: 0.195
inflation_radius: 0.12 # 0.8 # 1.0 # 0.1
cost_scaling_factor: 8.0 # 3.0 # 2.5 # 2.0 # 3.0
map_type: costmap
#transform_tolerance: 1
observation_sources: scan
scan: {data_type: LaserScan, topic: /limo/scan, marking: true, clearing: true}
track_unknown_space: true