# teb_local_planner_params.yaml
TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map
  teb_autosize: true
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 5.0
  feasibility_check_no_poses: 3
  min_obstacle_dist: 0.1
  inflation_dist: 0.1
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 2.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 2.0
  weight_kinematics_turning_radius: 1.0
  weight_optimaltime: 2.0
  weight_obstacle: 50.0
  weight_viapoint: 2.0
  weight_dynamic_obstacle: 15.0
  weight_dynamic_obstacle_inflation: 0.1
  weight_adapt_factor: 2.0
  min_turning_radius: 0.35
  max_vel_x: 0.4
  max_vel_x_backwards: 0.0
  max_vel_theta: 0.8
  acc_lim_x: 0.3
  acc_lim_theta: 0.4
  cmd_angle_instead_rotvel: true
  max_steering_angle: 0.6
  wheelbase: 0.2
  footprint_model:
    type: "polygon"
    vertices: [[-0.15, -0.1], [0.15, -0.1], [0.15, 0.1], [-0.15, 0.1]]
  weight_inflation: 2.5        # 障碍膨胀区域优化权重
  global_plan_viapoint_sep: 0.3
  global_plan_prune_distance: 0.5
  dt_ref: 0.3
  dt_hysteresis: 0.1
  holonomic_robot: false
  include_costmap_obstacles: true